In [1]:
import pandas as pd
data = pd.read_csv("customer_shopping_behavior.csv")

In [2]:
data.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [3]:
data.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [4]:
data["Review Rating"]=data.groupby("Category")["Review Rating"].transform(lambda x :x.fillna(x.median()))

In [5]:
data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [6]:
data.columns = data.columns.str.lower()
data.columns=data.columns.str.replace(" ","_")
data = data.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [7]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [8]:
labels= ["Young Adult","Adult","Middle-Aged","Senior"]
data["age_group"] = pd.qcut(data["age"],q=4,labels = labels)

In [9]:
frequency_mapping = {"Fortnightly":14,"Weekly":7,"Monthly":30,"Quarterly":90,"Bi-Weekly":14,"Annually":365,"Every 3 months":90}

data["purchase_frequency_days"]=data["frequency_of_purchases"].map(frequency_mapping)

In [10]:
data.drop("promo_code_used",axis=1)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7.0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-Aged,14.0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle-Aged,90.0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7.0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle-Aged,90.0

In [11]:
pip install psycopg2-binary alchemy

Requirement already satisfied: psycopg2-binary in c:\users\abhimanyu\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: alchemy in c:\users\abhimanyu\anaconda3\lib\site-packages (20.5)
Requirement already satisfied: requests==2.22.0 in c:\users\abhimanyu\anaconda3\lib\site-packages (from alchemy) (2.22.0)
Requirement already satisfied: python-daemon==2.2.4 in c:\users\abhimanyu\anaconda3\lib\site-packages (from alchemy) (2.2.4)
Requirement already satisfied: filelock==3.0.12 in c:\users\abhimanyu\anaconda3\lib\site-packages (from alchemy) (3.0.12)
Requirement already satisfied: docutils in c:\users\abhimanyu\anaconda3\lib\site-packages (from python-daemon==2.2.4->alchemy) (0.18.1)
Requirement already satisfied: lockfile>=0.10 in c:\users\abhimanyu\anaconda3\lib\site-packages (from python-daemon==2.2.4->alchemy) (0.12.2)
Requirement already satisfied: setuptools in c:\users\abhimanyu\anaconda3\lib\site-packages (from python-daemon==2.2.4->alchemy) (75.1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\abhimanyu\anaconda3\lib\site-packages (from requests==2.22.0->alchemy) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\abhimanyu\anaconda3\lib\site-packages (from requests==2.22.0->alchemy) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\abhimanyu\anaconda3\lib\site-packages (from requests==2.22.0->alchemy) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abhimanyu\anaconda3\lib\site-packages (from requests==2.22.0->alchemy) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

In [17]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

username = "postgres"
password = "Abhimanyu@18"
host = "localhost"
port = 5433
database = "customer_behaviour"

connection_url = URL.create(
    "postgresql+psycopg2",
    username=username,
    password=password,
    host=host,
    port=port,
    database=database
)

engine = create_engine(connection_url)

# Test connection
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [19]:
table_name = "customer"

data.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behaviour'.